// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'httpRequester'], function($, httpRequester) {
    var getMessages, resourceUrl, sendMessage, validateData;
    resourceUrl = 'http://crowd-chat.herokuapp.com/posts';
    validateData = function(input) {
      var isCorrectInput;
      isCorrectInput = $.type(input) === "string" && input.length > 0;
      if (!isCorrectInput) {
        throw new Error("Value for " + input + " must be string with length greater than 0");
      }
      return null;
    };
    sendMessage = function(userName, messageText) {
      var newPost;
      validateData(userName);
      validateData(messageText);
      newPost = {
        user: userName,
        text: messageText
      };
      return httpRequester.postJsonData(resourceUrl, newPost).then(function(data) {
        return alert("Post successful");
      }).fail(function(err) {
        return alert("Error: " + err);
      });
    };
    getMessages = function() {
      return httpRequester.getJsonData(resourceUrl);
    };
    return {
      sendMessage: sendMessage,
      getMessages: getMessages
    };
  });

}).call(this);

//# sourceMappingURL=persister.map
