// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'sammy', 'mustache'], function($, Sammy, Mustache) {
    var $chatForm, $crowdDisplay, $getPostsButton, $messageInput, $nameInput, $sendButton, escapeInput, getGetPostsButton, getNewPost, getSubmitButton, showMessages;
    $chatForm = $('#chat');
    $crowdDisplay = $('#app');
    $nameInput = $chatForm.find('#name');
    $messageInput = $chatForm.find('#message');
    $sendButton = $chatForm.find('#btn-send');
    $getPostsButton = $chatForm.find('#btn-get-posts');
    escapeInput = function(s) {
      return s.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    };
    getSubmitButton = function() {
      return $sendButton;
    };
    getGetPostsButton = function() {
      return $getPostsButton;
    };
    getNewPost = function() {
      var text, user;
      user = escapeInput($nameInput.val());
      text = escapeInput($messageInput.val());
      return {
        user: user,
        text: text
      };
    };
    showMessages = function(data) {
      var posts, template;
      template = "Messages:<ul>{{#.}}\n  <dl>\n    <dt>name: {{by}}</dt>\n      <dd>message: {{{text}}}</dd>\n  </dl>\n{{/.}}</ul>";
      posts = Mustache.to_html(template, data);
      return $crowdDisplay.html(posts);
    };
    return {
      getSubmitButton: getSubmitButton,
      getGetPostsButton: getGetPostsButton,
      getNewPost: getNewPost,
      showMessages: showMessages
    };
  });

}).call(this);

//# sourceMappingURL=view.map
