// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;   

namespace T4Sample
{
	public class T4SampleClass
	{
	   public static void HelloTFour()
	   {
		  Console.WriteLine("Hello, T4 Template");
	   }
	}
}
