// Generated by CoffeeScript 1.7.1
(function() {
  require.config({
    paths: {
      Q: 'bower_components/q/q',
      jquery: 'bower_components/jquery/dist/jquery',
      httpRequester: 'scripts/httpRequester',
      mustache: 'bower_components/mustache/mustache',
      persister: 'scripts/persister',
      ui: 'scripts/ui'
    }
  });

  require(['scripts/controller'], function(mainApp) {
    mainApp.run();
    return null;
  });

}).call(this);

//# sourceMappingURL=main.map
