// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery'], function($) {
    var controller;
    controller = (function() {
      var getPosts;
      getPosts = function(properties) {
        var requestJson;
        requestJson = {
          consumerKey: properties.consumerKey,
          consumerSecret: properties.consumerSecret,
          accessToken: properties.accessToken,
          accessTokenSecret: properties.accessTokenSecret,
          username: properties.username,
          count: properties.numberOfPosts
        };
        return $.ajax({
          url: 'http://localhost:3000/tweets',
          type: 'POST',
          data: JSON.stringify(requestJson),
          contentType: 'application/json',
          success: function(data) {
            return data;
          }
        });
      };
      return {
        getPosts: getPosts
      };
    })();
    return controller;
  });

}).call(this);

//# sourceMappingURL=twitterAPIcontroller.map
