// Generated by CoffeeScript 1.7.1
(function() {
  require.config({
    paths: {
      Q: 'bower_components/q/q',
      jquery: 'bower_components/jquery/dist/jquery',
      mustache: 'bower_components/mustache/mustache',
      sammy: 'bower_components/sammy/lib/sammy',
      persister: 'scripts/persister',
      httpRequester: 'scripts/httpRequester',
      view: 'scripts/view'
    }
  });

  require(['scripts/controller'], function(controller) {
    controller.run();
    return null;
  });

}).call(this);

//# sourceMappingURL=main.map
