// Generated by CoffeeScript 1.7.1
(function() {
  describe('#persister', function() {
    return it('should throw an exception if incorrect name', function() {
      return addStudent([], 4);
    });
  });

}).call(this);

//# sourceMappingURL=test.map
