// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'persister', 'ui'], function($, persister, ui) {
    var run;
    run = function() {
      var $addButton, $addForm, $delButton, $delInput, $getButton, $getDelForm, $gradeInput, $nameInput, addStudent, delStudent, getStudents;
      $addForm = $('#student-input');
      $getDelForm = $('#get-del-student');
      $nameInput = $addForm.find('#tb-st-name');
      $gradeInput = $addForm.find('#tb-st-grade');
      $addButton = $addForm.find('#btn-add');
      $delInput = $getDelForm.find('#tb-del-id');
      $getButton = $getDelForm.find('#btn-get');
      $delButton = $getDelForm.find('#btn-del');
      addStudent = function(ev) {
        var grade, name;
        ev.preventDefault();
        name = $nameInput.val();
        grade = parseInt($gradeInput.val());
        return persister.addStudent(name, grade).then(function(data) {
          return ui.showMessage("Addition successful");
        }).fail(function(err) {
          return ui.showMessage("Error: " + err);
        });
      };
      getStudents = function(ev) {
        ev.preventDefault();
        return persister.getStudents().then(function(data) {
          return ui.displayStudents(data);
        }).fail(function(err) {
          return ui.showMessage("Error: " + err);
        });
      };
      delStudent = function(ev) {
        var idToDelete;
        ev.preventDefault();
        idToDelete = $delInput.val();
        return persister.delStudent(idToDelete).then(function(data) {
          ui.showMessage("Student " + idToDelete + " was deleted successfully");
          return getStudents(ev);
        }).fail(function(err) {
          return ui.showMessage("Error: " + err);
        });
      };
      $addButton.on('click', addStudent);
      $getButton.on('click', getStudents);
      return $delButton.on('click', delStudent);
    };
    return {
      run: run
    };
  });

}).call(this);

//# sourceMappingURL=controller.map
